Adding Contact Form
Wolfmikerson/Portfolio_V3 pull request #1
Opened 2022-11-03 08:16 UTC by Wolfmikerson

- Add a contact form to index.html
- Style the contact form wt CSS styling
- Verify the data was sent properly

2022-11-03 08:40 UTC, christianbiring1 requested changes
Hi @Wolfmikerson , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/199677166-45423393-b7e9-451e-a5bd-cd8ab6b0b153.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Good commit messages :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] `I HIGHLY RECOMMEND YOU IMPLEMENT THEM FOR THEY WIL TAKE YOUR PROJECT TO THE NEXT LEVEL` :rocket: 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 08:40 UTC, christianbiring1 commented on css/style.css
> +  }
- [ ]  Kindly consider removing this block of code as it doesn't make your codebase looks clean

2022-11-03 08:40 UTC, christianbiring1 commented on css/style.css
> +}
[OPTIONAL]
- [ ] Kindly make sure your page is responsive on small-screen devices for accessibility purposes
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/199676723-2a34a1e5-e807-4ae2-9199-61ced19b314d.png)

![image](https://user-images.githubusercontent.com/97100091/199676290-46e6e790-2cbd-4a2f-8893-bfab712a0ddc.png)
![image](https://user-images.githubusercontent.com/97100091/199676649-0703abd9-4b97-4f08-9270-18b579167dcb.png)


Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/199676412-ab25f349-47e9-4a56-8e23-6db5a687a72e.png)

2022-11-03 08:40 UTC, christianbiring1 commented on index.html
>          <ul class="list-item default-list-style">
[OPTIONAL]
- [ ] For accessibility purposes, kindly make sure all your card titles as grabbed in a header tag `hx` and not a paragraph as is the case in your code

2022-11-04 02:08 UTC, Owusu-Desmond requested changes
Hi @Wolfmikerson  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media4.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented
:heavy_check_mark: Good PR description 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 02:08 UTC, Owusu-Desmond commented on css/style.css
> +  }
- [ ] As requested by the previous code reviewer, you should consider removing this block of code as it doesn't make your codebase looks clean. You can read this article for more details telling the reason why committing commented code is bad. [Please, don't commit commented-out code - Kent C. Dodds](https://kentcdodds.com/blog/please-dont-commit-commented-out-code)

2022-11-04 10:37 UTC, Kamba56 reviewed
Hi  @Wolfmikerson, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **Does not run linters checks **. Kindly make sure that all linters checks are running and submit for a re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-04 16:57 UTC, Owusu-Desmond approved these changes
Hi @Wolfmikerson  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 16:59 UTC, merged